In [1]:
import pandas as pd


In [18]:
df = pd.read_csv('corona_csv.csv', encoding='unicode-escape',index_col=0)
#skiprows parameter skips rows from start.
df.head()

Country, Other  Total Cases New Cases Total Deaths  New Deaths  \
#                                                                  
1            USA  3,45,40,866        21     6,20,250         1.0   
2          India  3,04,32,670    22,093     3,99,720       245.0   
3         Brazil  1,85,59,164       NaN     5,18,246         NaN   
4         France    57,75,301       NaN     1,11,082         NaN   
5         Russia    55,38,142    23,543     1,35,886       672.0   

  Total Recovered New Recovered Active Cases Serious, Critical  \
#                                                                
1     2,90,26,688           NaN    48,93,928             3,891   
2     2,94,98,619        17,097     5,34,331             8,944   
3     1,68,58,632           NaN    11,82,286             8,318   
4       56,18,885           NaN       45,334             1,204   
5       50,17,321        16,928     3,84,935             2,300   

  Tot Cases/ 1M pop Deaths/ 1M pop   Total Tests Tests/ 1M pop      Population  
#                                                                               
1          1,03,747          1,863  50,61,59,128     15,20,297    33,29,34,343  
2            21,839            287  41,20,21,494      2,95,675  1,39,34,94,216  
3            86,700          2,421   5,32,09,627      2,48,570    21,40,62,708  
4            88,284          1,698   9,30,89,184     14,23,004     6,54,17,371  
5            37,933            931  15,01,21,327     10,28,251    14,59,96,812

In [10]:
#For Reading text files(read_table) 
#df = pd.read_table("corona_textfile.txt")

In [19]:
#WE CAN SPECIFY SHEET OF EXCEL FILE
df = pd.read_excel('corona_excel.xlsx',sheet_name='Sheet1',index_col=0)

In [22]:
#MAKING A COLUMN AS INDEX OF DATAFRAME
df.set_index('Country, Other',inplace=True)

In [24]:
#RESETTING INDEX
df.reset_index()

Country, Other  Total Cases  New Cases  Total Deaths  New Deaths  \
0                 USA     34540866       21.0      620250.0         1.0   
1               India     30432670    22093.0      399720.0       245.0   
2              Brazil     18559164        NaN      518246.0         NaN   
3              France      5775301        NaN      111082.0         NaN   
4              Russia      5538142    23543.0      135886.0       672.0   
..                ...          ...        ...           ...         ...   
217           Vanuatu            4        NaN           1.0         NaN   
218  Marshall Islands            4        NaN           NaN         NaN   
219             Samoa            3        NaN           NaN         NaN   
220      Saint Helena            2        NaN           NaN         NaN   
221        Micronesia            1        NaN           NaN         NaN   

     Total Recovered  New Recovered  Active Cases  Serious, Critical  \
0         29026688.0            NaN     4893928.0             3891.0   
1         29498619.0        17097.0      534331.0             8944.0   
2         16858632.0            NaN     1182286.0             8318.0   
3          5618885.0            NaN       45334.0             1204.0   
4          5017321.0        16928.0      384935.0             2300.0   
..               ...            ...           ...                ...   
217              3.0            NaN           0.0                NaN   
218              4.0            NaN           0.0                NaN   
219              3.0            NaN           0.0                NaN   
220              2.0            NaN           0.0                NaN   
221              1.0            NaN           0.0                NaN   

     Tot Cases/ 1M pop  Deaths/ 1M pop  Total Tests  Tests/ 1M pop  \
0             103747.0          1863.0  506159128.0      1520297.0   
1              21839.0           287.0  412021494.0       295675.0   
2              86700.0          2421.0   53209627.0       248570.0   
3              88284.0          1698.0   93089184.0      1423004.0   
4              37933.0           931.0  150121327.0      1028251.0   
..                 ...             ...          ...            ...   
217               13.0             3.0      23000.0        73189.0   
218               67.0             NaN          NaN            NaN   
219               15.0             NaN          NaN            NaN   
220              328.0             NaN          NaN            NaN   
221                9.0             NaN          NaN            NaN   

       Population  
0    3.329343e+08  
1    1.393494e+09  
2    2.140627e+08  
3    6.541737e+07  
4    1.459968e+08  
..            ...  
217  3.142550e+05  
218  5.958700e+04  
219  1.997260e+05  
220  6.095000e+03  
221  1.162220e+05  

[222 rows x 14 columns]

In [25]:
from sklearn import datasets

In [28]:
#THIS IS DATASET FOR UNSUPERVISED LEARNING
table = datasets.make_circles()

In [32]:
#THIS IS DATASET FOR SUPERVISED LEARNING
table_ = datasets.load_boston()
table_.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename'])

In [34]:
df_ = pd.DataFrame(data = table_['data'],columns = table_['feature_names'])

In [36]:
df_.dtypes

CRIM       float64
ZN         float64
INDUS      float64
CHAS       float64
NOX        float64
RM         float64
AGE        float64
DIS        float64
RAD        float64
TAX        float64
PTRATIO    float64
B          float64
LSTAT      float64
dtype: object

In [40]:
df_.describe(include = 'all', percentiles=[0.1,0.2,0.9])

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.284634   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.702617   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
10%      0.038195    0.000000    2.910000    0.000000    0.427000    5.593500   
20%      0.064170    0.000000    4.390000    0.000000    0.442000    5.837000   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208500   
90%     10.753000   42.500000   19.580000    0.000000    0.713000    7.151500   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
10%     26.950000    1.628300    3.000000  233.000000   14.750000  290.270000   
20%     37.800000    1.951200    4.000000  273.000000   16.600000  364.310000   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
90%     98.800000    6.816600   24.000000  666.000000   20.900000  396.900000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT  
count  506.000000  
mean    12.653063  
std      7.141062  
min      1.730000  
10%      4.680000  
20%      6.290000  
50%     11.360000  
90%     23.035000  
max     37.970000

In [42]:
df_.drop_duplicates(inplace=True)
df_.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [88]:
#default axis is rows(0).
df_.drop(list(range(0,len(df_),2)))

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
5    0.02985   0.0   2.18   0.0  0.458  6.430  58.7  6.0622  3.0  222.0   
7    0.14455  12.5   7.87   0.0  0.524  6.172  96.1  5.9505  5.0  311.0   
9    0.17004  12.5   7.87   0.0  0.524  6.004  85.9  6.5921  5.0  311.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
497  0.26838   0.0   9.69   0.0  0.585  5.794  70.6  2.8927  6.0  391.0   
499  0.17783   0.0   9.69   0.0  0.585  5.569  73.5  2.3999  6.0  391.0   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  
1       17.8  396.90   9.14  
3       18.7  394.63   2.94  
5       18.7  394.12   5.21  
7       15.2  396.90  19.15  
9       15.2  386.71  17.10  
..       ...     ...    ...  
497     19.2  396.90  14.10  
499     19.2  395.77  15.10  
501     21.0  391.99   9.67  
503     21.0  396.90   5.64  
505     21.0  396.90   7.88  

[253 rows x 13 columns]

In [46]:
import numpy as np

In [65]:
m1 = np.matrix([[1,4],[2,3]])
m1

matrix([[1, 4],
        [2, 3]])

In [67]:
m1.conjugate()

matrix([[1, 4],
        [2, 3]])

In [60]:
m1.I

matrix([[-0.6,  0.8],
        [ 0.4, -0.2]])

In [63]:
m1.transpose()

matrix([[1, 2],
        [4, 3]])

In [69]:
m2 = np.matrix("0 0 0 ; 1 1 1 ; 2 2 2")

In [72]:
m2.reshape(1,9)

matrix([[0, 0, 0, 1, 1, 1, 2, 2, 2]])

In [77]:
a = m1.getI()

In [78]:
m1 * a

matrix([[ 1.00000000e+00,  0.00000000e+00],
        [-1.11022302e-16,  1.00000000e+00]])

In [79]:
m1

matrix([[1, 4],
        [2, 3]])

In [81]:
for i in m1:
    print(i)

[[1 4]]
[[2 3]]


In [85]:
!pip install klib

NameError: name 'klib' is not defined